version: '3'
services:
  discordDownloader:
    image: tyrrrz/discordchatexporter:2.30.1
    container_name: discordDownloader
    entrypoint: /bin/loop.sh $CHANNEL_ID $DISCORD_TOKEN
    volumes:
      - ./downloader/loop.sh:/bin/loop.sh
      - ./output:/var/output
    env_file:
      - .env
  # OpenTelemetry Collector
  otelcollector:
    image:  otel/opentelemetry-collector-contrib:0.40.0
    container_name: otelcollector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      - ./output:/output
    depends_on:
      - splunk
  # Splunk Enterprise server:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_HEC_TOKEN=00000000-0000-0000-0000-0000000000000
    ports:
      - 18000:8000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000']
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./splunk.yml:/tmp/defaults/default.yml
      - /opt/splunk/var
      - /opt/splunk/etc
      - ./TA_discord:/opt/splunk/etc/apps/TA_discord/
